backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "original-poetry"
    label: "Original Poetry"
    folder: "content/original-poetry"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          soft_wrap: true,
          hint: "Use Shift+Enter at the end of a line to force a new line but not paragraph.",
        }
      - {
          label: "Order",
          name: "order",
          widget: "number",
          default: 1,
          hint: "Note: Poems with higher order will appear above poems with lower order. If poems have the same order number, they will be sorted alphabetically.",
        }
    sortable_fields:
      - "title"
      - "order"
    summary: "{{title}} (Order: {{order}})"

  - name: "translated-poetry"
    label: "Translated Poetry"
    folder: "content/translated-poetry"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Details",
          name: "details",
          widget: "markdown",
          hint: "Details about original poem. This details will be shown in a paragraph above title.",
        }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          soft_wrap: true,
          hint: "Use Shift+Enter at the end of a line to force a new line but not paragraph.",
        }
      - {
          label: "Order",
          name: "order",
          widget: "number",
          default: 1,
          hint: "Note: Poems with higher order will appear above poems with lower order. If poems have the same order number, they will be sorted alphabetically.",
        }
    sortable_fields:
      - "title"
      - "order"
    summary: "{{title}} (Order: {{order}})"

  - name: "original-prose"
    label: "Original Prose"
    folder: "content/original-prose"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          soft_wrap: true,
          required: false,
          hint: "Use this field if the prose has no chapters.",
        }
      - {
          label: "Chapters",
          name: "chapters",
          widget: "list",
          fields:
            [
              {
                label: "Chapter Title",
                name: "chapter_title",
                widget: "string",
              },
              {
                label: "Body",
                name: "body",
                widget: "markdown",
                soft_wrap: true,
              },
            ],
          hint: "Use this field if the prose has chapters. Leave blank if not applicable.",
        }
      - {
          label: "Order",
          name: "order",
          widget: "number",
          default: 1,
          hint: "Note: Prose with higher order will appear above prose with lower order. If prose have the same order number, they will be sorted alphabetically.",
        }
    sortable_fields:
      - "title"
      - "order"
    summary: "{{title}} (Order: {{order}})"

  - name: "translated-prose"
    label: "Translated Prose"
    folder: "content/translated-prose"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          name: "chapters",
          label: "Chapters",
          widget: "list",
          fields:
            [
              {
                label: "Chapter Title",
                name: "chapter_title",
                widget: "string",
              },
              {
                label: "Body",
                name: "body",
                widget: "markdown",
                soft_wrap: true,
              },
              {
                label: "Excerpt Note",
                name: "excerpt_note",
                widget: "string",
                required: false,
                hint: "This note will appear at top of the chapter, before the title.",
              },
            ],
        }
      - {
          label: "Order",
          name: "order",
          widget: "number",
          default: 1,
          hint: "Note: Prose with higher order will appear above prose with lower order. If prose have the same order number, they will be sorted alphabetically.",
        }
    sortable_fields:
      - "title"
      - "order"
    summary: "{{title}} (Order: {{order}})"
