backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "original-poetry"
    label: "Original Poetry"
    folder: "content/original-poetry"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          soft_wrap: true,
          hint: "Use two spaces at the end of a line to force a new line.",
        }

  - name: "translated-poetry"
    label: "Translated Poetry"
    folder: "content/translated-poetry"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          soft_wrap: true,
          hint: "Use two spaces at the end of a line to force a new line.",
        }
